### ISSUE TITLE
Two functions report errors in the code

### ISSUE THREAD

**Issue by libig1012** [shivgahlout/Robust-Classification-with-Convolutional-Prototype-Learning-Pytorch#1]
plots(epochs, train_acc, test_acc, train_loss, test_loss,plotsFileName)
write_csv(csvFileName, train_acc,test_acc,train_loss,test_loss,epoch)

**Comment by shivgahlout** [comment]
I noticed that data_utils.py  that contains these functions is missing. Main code is independent of this file. You can comment the these two functions.
